# Auto-generated by scripts/sync-alpine.sh
# Source: Alpine Linux aports (main/bc)
# Package: bc 1.08.2-r0
# Generated: 2026-02-27T21:58:26Z

set(ALPINE_PKGNAME "bc")
set(ALPINE_PKGVER "1.08.2")

set(ALPINE_SOURCE_URLS
    "https://ftp.gnu.org/gnu/bc/bc-1.08.2.tar.gz"
)
set(ALPINE_SOURCE_FILENAME "bc-1.08.2.tar.gz")
set(ALPINE_SOURCE_SHA512 0876a4c5bfc23da79479519c6a8e03ac9f59ae54077eb71ffdcc6ddaccb76c4b7595b088e89e6ad82d833c072eeff5b378178084276584813c00eedace4c6f8c)

set(ALPINE_PATCHES)
