# Auto-generated by scripts/sync-alpine.sh
# Source: Alpine Linux aports (main/jq)
# Package: jq 1.8.1-r0
# Generated: 2026-02-27T21:58:27Z

set(ALPINE_PKGNAME "jq")
set(ALPINE_PKGVER "1.8.1")

set(ALPINE_SOURCE_URLS
    "https://github.com/jqlang/jq/releases/download/jq-1.8.1/jq-1.8.1.tar.gz"
)
set(ALPINE_SOURCE_FILENAME "jq-1.8.1.tar.gz")
set(ALPINE_SOURCE_SHA512 b09d48dbeaac7b552397b75692ed7833afa72186de80d977fb1b887a14ac66c02f677acdd79f9a2736db1fd738b7ce57a39725e34846bfa21ed3728cd7adc187)

set(ALPINE_PATCHES
    test-portable.patch
)
