# Auto-generated by scripts/sync-alpine.sh
# Source: Alpine Linux aports (community/lzop)
# Package: lzop 1.04-r1
# Generated: 2026-02-27T21:58:27Z

set(ALPINE_PKGNAME "lzop")
set(ALPINE_PKGVER "1.04")

set(ALPINE_SOURCE_URLS
    "https://www.lzop.org/download/lzop-1.04.tar.gz"
)
set(ALPINE_SOURCE_FILENAME "lzop-1.04.tar.gz")
set(ALPINE_SOURCE_SHA512 5829b4495ffefab549aa697a05c536ce593c572c9eee6004460583a0090abcd317c6074c4f981dfee6be61ac8d127f02dd37053b6cb782af64db41586a8bbb6e)

set(ALPINE_PATCHES)
