# Auto-generated by scripts/sync-alpine.sh
# Source: Alpine Linux aports (main/util-linux)
# Package: util-linux 2.40.4-r1
# Generated: 2026-03-02T00:00:00Z

set(ALPINE_PKGNAME "util-linux")
set(ALPINE_PKGVER "2.40.4")

set(ALPINE_SOURCE_URLS
    "https://www.kernel.org/pub/linux/utils/util-linux/v2.40/util-linux-2.40.4.tar.xz"
)
set(ALPINE_SOURCE_FILENAME "util-linux-2.40.4.tar.xz")
set(ALPINE_SOURCE_SHA512 0024955056ba7b4c54040a917f9919f49692e57ba6d42d17a6c29c1eefe88bf48b1214a545072b71c468829a63a8f15237f49733e9127c134e11126d1e435124)

set(ALPINE_PATCHES)
