# Auto-generated by scripts/sync-alpine.sh
# Source: Alpine Linux aports (main/diffutils)
# Package: diffutils 3.12-r0
# Generated: 2026-02-27T21:58:26Z

set(ALPINE_PKGNAME "diffutils")
set(ALPINE_PKGVER "3.12")

set(ALPINE_SOURCE_URLS
    "https://ftp.gnu.org/pub/gnu/diffutils/diffutils-3.12.tar.xz"
)
set(ALPINE_SOURCE_FILENAME "diffutils-3.12.tar.xz")
set(ALPINE_SOURCE_SHA512 10b17cf1dcdfa9ca0e5db91d62c4a079ebe9fd7eafa3aaebd4eb7e6206e4d753f348496622aa281e1bd7f7fcde65ce4a886dcc4acbb59332ef980f224197b4e4)

set(ALPINE_PATCHES
    skip-meaningless-pthread-rwlock-test.patch
)
