# Auto-generated by scripts/sync-alpine.sh
# Source: Alpine Linux aports (main/grep)
# Package: grep 3.12-r0
# Generated: 2026-02-27T21:58:26Z

set(ALPINE_PKGNAME "grep")
set(ALPINE_PKGVER "3.12")

set(ALPINE_SOURCE_URLS
    "https://mirrors.kernel.org/gnu/grep/grep-3.12.tar.xz"
)
set(ALPINE_SOURCE_FILENAME "grep-3.12.tar.xz")
set(ALPINE_SOURCE_SHA512 c54b4db5a8b9afe098c088decd94977746305284d716666a60bac82b4edc0fae4acf828970b5b6fc7d58ecd549f638e17e6958f33a71fedcc7d7415b9228b161)

set(ALPINE_PATCHES)
