# Auto-generated by scripts/sync-alpine.sh
# Source: Alpine Linux aports (main/sed)
# Package: sed 4.9-r2
# Generated: 2026-02-27T21:58:27Z

set(ALPINE_PKGNAME "sed")
set(ALPINE_PKGVER "4.9")

set(ALPINE_SOURCE_URLS
    "https://ftp.gnu.org/pub/gnu/sed/sed-4.9.tar.xz"
)
set(ALPINE_SOURCE_FILENAME "sed-4.9.tar.xz")
set(ALPINE_SOURCE_SHA512 36157a4b4a2430cf421b7bd07f1675d680d9f1616be96cf6ad6ee74a9ec0fe695f8d0b1e1f0b008bbb33cc7fcde5e1c456359bbbc63f8aebdd4fedc3982cf6dc)

set(ALPINE_PATCHES)
