# Auto-generated by scripts/sync-alpine.sh
# Source: Alpine Linux aports (main/netcat-openbsd)
# Package: netcat-openbsd 1.226.1.1-r0
# Generated: 2026-03-02T00:00:00Z

set(ALPINE_PKGNAME "netcat-openbsd")
set(ALPINE_PKGVER "1.226.1.1")

set(ALPINE_SOURCE_URLS
    "https://salsa.debian.org/debian/netcat-openbsd/-/archive/debian/1.226-1.1/netcat-openbsd-debian-1.226-1.1.tar.gz"
)
set(ALPINE_SOURCE_FILENAME "netcat-openbsd-debian-1.226-1.1.tar.gz")
set(ALPINE_SOURCE_SHA512 3a7aef24555d007b108f4b628d9d5f3f4490a8c2312395926b6e35f204cce55fcaefa06c62b9e3a931a4eb6b2008892a3764f91fd8eb59b44327a16ac80d8619)

set(ALPINE_PATCHES
    b64.patch
)
