#!/bin/sh
# gen_busyq_applets.sh - Generate BUSYQ_BB_APPLET() entries from busybox build
#
# Parses busybox's generated include/applets.h to extract the applet
# names, main functions, and flags (NOFORK/NOEXEC).
#
# Usage: gen_busyq_applets.sh <busybox-build-dir> <output-header>

set -eu

BB_BUILD="$1"
OUTPUT="$2"

APPLETS_H="$BB_BUILD/include/applets.h"
if [ ! -f "$APPLETS_H" ]; then
    echo "/* WARNING: Could not find applets.h, empty table */" > "$OUTPUT"
    exit 0
fi

cat > "$OUTPUT" << 'HEADER'
/*
 * busybox_applets.h - Auto-generated busybox applet table for busyq
 *
 * Generated by gen_busyq_applets.sh from busybox's include/applets.h
 * DO NOT EDIT - this file is regenerated during the build.
 *
 * Each entry is: BUSYQ_BB_APPLET(name_string, main_func, flags)
 * where flags is 0, BUSYQ_APPLET_NOFORK, or BUSYQ_APPLET_NOEXEC
 */
HEADER

# The file has lines like:
#   IF_xxx(APPLET(name, BB_DIR_xxx, BB_SUID_xxx))
#   IF_xxx(APPLET_NOFORK(name, main, BB_DIR_xxx, BB_SUID_xxx, help))
#   IF_xxx(APPLET_NOEXEC(name, main, BB_DIR_xxx, BB_SUID_xxx, help))
#   IF_xxx(APPLET_ODDNAME(name, main, BB_DIR_xxx, BB_SUID_xxx, help))
#
# We only care about lines starting with IF_ (actual applet registrations,
# not #define lines).

# Filter to just IF_ lines (actual applet registrations)
grep '^IF_' "$APPLETS_H" > /tmp/applet_lines.txt || true

# APPLET_NOFORK(name, main, ...) -> name_main with NOFORK flag
grep 'APPLET_NOFORK' /tmp/applet_lines.txt | \
    sed 's/.*APPLET_NOFORK(//;s/)).*//' | \
    while IFS=',' read -r name main rest; do
        name=$(echo "$name" | tr -d ' ')
        main=$(echo "$main" | tr -d ' ')
        echo "BUSYQ_BB_APPLET(\"$name\", ${main}_main, BUSYQ_APPLET_NOFORK)"
    done >> "$OUTPUT"

# APPLET_NOEXEC(name, main, ...) -> name_main with NOEXEC flag
grep 'APPLET_NOEXEC' /tmp/applet_lines.txt | \
    sed 's/.*APPLET_NOEXEC(//;s/)).*//' | \
    while IFS=',' read -r name main rest; do
        name=$(echo "$name" | tr -d ' ')
        main=$(echo "$main" | tr -d ' ')
        echo "BUSYQ_BB_APPLET(\"$name\", ${main}_main, BUSYQ_APPLET_NOEXEC)"
    done >> "$OUTPUT"

# APPLET_ODDNAME(name, main, ...) -> main_main with no special flags
grep 'APPLET_ODDNAME' /tmp/applet_lines.txt | \
    sed 's/.*APPLET_ODDNAME(//;s/)).*//' | \
    while IFS=',' read -r name main rest; do
        name=$(echo "$name" | tr -d ' ')
        main=$(echo "$main" | tr -d ' ')
        echo "BUSYQ_BB_APPLET(\"$name\", ${main}_main, 0)"
    done >> "$OUTPUT"

# Regular APPLET(name, ...) -> name_main with no special flags
# Exclude lines already handled above
grep 'APPLET(' /tmp/applet_lines.txt | \
    grep -v 'APPLET_NOFORK\|APPLET_NOEXEC\|APPLET_ODDNAME\|APPLET_SCRIPTED' | \
    sed 's/.*APPLET(//;s/)).*//' | \
    while IFS=',' read -r name rest; do
        name=$(echo "$name" | tr -d ' ')
        echo "BUSYQ_BB_APPLET(\"$name\", ${name}_main, 0)"
    done >> "$OUTPUT"

echo "/* End of generated applet table */" >> "$OUTPUT"
count=$(grep -c BUSYQ_BB_APPLET "$OUTPUT" || true)
echo "Generated $count applet entries in $OUTPUT"

rm -f /tmp/applet_lines.txt
