#!/bin/sh
# gen_busyq_applets.sh - Generate BUSYQ_BB_APPLET() entries from busybox build
#
# Preprocesses busybox's include/applets.h with autoconf.h so that IF_xxx
# macros filter out disabled applets.  The default (#else) branch of
# applets.h emits struct literals whose field count distinguishes types:
#   { "name", "main", dir, suid }          → regular/ODDNAME (4 fields)
#   { "name", "main", dir, suid, 1 }       → NOEXEC          (5 fields)
#   { "name", "main", dir, suid, 1, 1 }    → NOFORK          (6 fields)
#
# Usage: gen_busyq_applets.sh <busybox-build-dir> <output-header>

set -eu

BB_BUILD="$1"
OUTPUT="$2"

APPLETS_H="$BB_BUILD/include/applets.h"
if [ ! -f "$APPLETS_H" ]; then
    echo "/* WARNING: Could not find applets.h, empty table */" > "$OUTPUT"
    exit 0
fi

cat > "$OUTPUT" << 'HEADER'
/*
 * busybox_applets.h - Auto-generated busybox applet table for busyq
 *
 * Generated by gen_busyq_applets.sh from busybox's include/applets.h
 * DO NOT EDIT - this file is regenerated during the build.
 *
 * Each entry is: BUSYQ_BB_APPLET(name_string, main_func, flags)
 * where flags is 0, BUSYQ_APPLET_NOFORK, or BUSYQ_APPLET_NOEXEC
 */
HEADER

# Preprocess with autoconf.h.  No control macros defined → falls into
# the #else branch which emits { "name", "main", dir, suid[, noexec[, nofork]] }
cc -E -include "$BB_BUILD/include/autoconf.h" "$APPLETS_H" 2>/dev/null | \
    grep '^{' | \
    sed 's/[{}]//g; s/,/ /g' | \
    while read -r name main dir suid noexec nofork rest; do
        # Strip quotes from name and main
        name=$(echo "$name" | tr -d '"' | tr -d ' ')
        main=$(echo "$main" | tr -d '"' | tr -d ' ')
        if [ -n "$nofork" ]; then
            echo "BUSYQ_BB_APPLET(\"$name\", ${main}_main, BUSYQ_APPLET_NOFORK)"
        elif [ -n "$noexec" ]; then
            echo "BUSYQ_BB_APPLET(\"$name\", ${main}_main, BUSYQ_APPLET_NOEXEC)"
        else
            echo "BUSYQ_BB_APPLET(\"$name\", ${main}_main, 0)"
        fi
    done >> "$OUTPUT"

echo "/* End of generated applet table */" >> "$OUTPUT"
count=$(grep -c BUSYQ_BB_APPLET "$OUTPUT" || true)
echo "Generated $count applet entries in $OUTPUT"
