# Auto-generated by scripts/sync-alpine.sh
# Source: Alpine Linux aports (main/less)
# Package: less 685-r0
# Generated: 2026-02-27T21:58:27Z

set(ALPINE_PKGNAME "less")
set(ALPINE_PKGVER "685")

set(ALPINE_SOURCE_URLS
    "https://www.greenwoodsoftware.com/less/less-685.tar.gz"
)
set(ALPINE_SOURCE_FILENAME "less-685.tar.gz")
set(ALPINE_SOURCE_SHA512 aff745f1816e0f996fbdbc33ecae0726cf0d842efc227937ff8c32e734c8b5be4c611ffbb27e5e038b4d95280c95ca60c53af1a47cf419cb06e5fab543c231f3)

set(ALPINE_PATCHES)
