# Auto-generated by scripts/sync-alpine.sh
# Source: Alpine Linux aports (community/cpio)
# Package: cpio 2.15-r0
# Generated: 2026-02-27T21:58:26Z

set(ALPINE_PKGNAME "cpio")
set(ALPINE_PKGVER "2.15")

set(ALPINE_SOURCE_URLS
    "https://ftp.gnu.org/gnu/cpio/cpio-2.15.tar.bz2"
)
set(ALPINE_SOURCE_FILENAME "cpio-2.15.tar.bz2")
set(ALPINE_SOURCE_SHA512 e3c3d0344d13d540887198ee5d6209a9254ed34b87c3b3cabe6dc3ce22ef94d3f380bb60d3395eee44e4b0ec8460b957032c6251f101b4a9fbc5951a701aadff)

set(ALPINE_PATCHES
    gcc15.patch
)
