# Auto-generated by scripts/sync-alpine.sh
# Source: Alpine Linux aports (community/dos2unix)
# Package: dos2unix 7.5.3-r0
# Generated: 2026-02-27T21:58:26Z

set(ALPINE_PKGNAME "dos2unix")
set(ALPINE_PKGVER "7.5.3")

set(ALPINE_SOURCE_URLS
    "https://waterlan.home.xs4all.nl/dos2unix/dos2unix-7.5.3.tar.gz"
)
set(ALPINE_SOURCE_FILENAME "dos2unix-7.5.3.tar.gz")
set(ALPINE_SOURCE_SHA512 c586a3c8b3e800a58cfa66ec9f4f6ea5b2c5d3c5dbcc9e4f22798ddb89d2f29f1eba1b8102fd948be0b978b517b25a9f5f469eda215116a31170f223d46f3394)

set(ALPINE_PATCHES)
