# Auto-generated by scripts/sync-alpine.sh
# Source: Alpine Linux aports (main/ed)
# Package: ed 1.22.2-r0
# Generated: 2026-02-27T21:58:26Z

set(ALPINE_PKGNAME "ed")
set(ALPINE_PKGVER "1.22.2")

set(ALPINE_SOURCE_URLS
    "https://ftp.gnu.org/gnu/ed/ed-1.22.2.tar.lz"
)
set(ALPINE_SOURCE_FILENAME "ed-1.22.2.tar.lz")
set(ALPINE_SOURCE_SHA512 4436ee0494e5b173dad5df86db1fa1f652316e529640f82655a312e7350998a2ec867de763f8842d8833473039838e8f462d4f01ffbb9b15a082ca28896ec349)

set(ALPINE_PATCHES)
