# Auto-generated by scripts/sync-alpine.sh
# Source: Alpine Linux aports (main/curl)
# Package: curl 8.17.0-r1
# Generated: 2026-02-27T21:58:26Z

set(ALPINE_PKGNAME "curl")
set(ALPINE_PKGVER "8.17.0")

set(ALPINE_SOURCE_URLS
    "https://curl.se/download/curl-8.17.0.tar.xz"
)
set(ALPINE_SOURCE_FILENAME "curl-8.17.0.tar.xz")
set(ALPINE_SOURCE_SHA512 fc6349def40c3c259de2a568631507df17dff83e78a2edbb93f069586dce594439fdc88bef7ce2bed7491f35800b8c0c181c8c88e6ef656cc3c18f9834681eca)

set(ALPINE_PATCHES
    reg-19383.patch
    reg-19408.patch
)
