# Auto-generated by scripts/sync-alpine.sh
# Source: Alpine Linux aports (main/xz)
# Package: xz 5.8.2-r0
# Generated: 2026-02-27T15:20:46Z

set(ALPINE_PKGNAME "xz")
set(ALPINE_PKGVER "5.8.2")

set(ALPINE_SOURCE_URLS
    "https://github.com/tukaani-project/xz/archive/refs/tags/v5.8.2/xz-5.8.2.tar.gz"
)
set(ALPINE_SOURCE_FILENAME "xz-5.8.2.tar.gz")
set(ALPINE_SOURCE_SHA512 a14c9d0a118c611d1156cd9a605269c706b976a752c048db7f2eea956e2bf717ce595f46186d951a6c4493e35658e08fa3fe4b256898c6ca08e3695c0ee7b0e5)

set(ALPINE_PATCHES)
