# Auto-generated by scripts/sync-alpine.sh
# Source: Alpine Linux aports (main/bzip2)
# Package: bzip2 1.0.8-r6
# Generated: 2026-02-27T21:58:26Z

set(ALPINE_PKGNAME "bzip2")
set(ALPINE_PKGVER "1.0.8")

set(ALPINE_SOURCE_URLS
    "https://sourceware.org/pub/bzip2/bzip2-1.0.8.tar.gz"
)
set(ALPINE_SOURCE_FILENAME "bzip2-1.0.8.tar.gz")
set(ALPINE_SOURCE_SHA512 083f5e675d73f3233c7930ebe20425a533feedeaaa9d8cc86831312a6581cefbe6ed0d08d2fa89be81082f2a5abdabca8b3c080bf97218a1bd59dc118a30b9f3)

set(ALPINE_PATCHES
    bzip2-1.0.4-makefile-CFLAGS.patch
    bzip2-1.0.4-man-links.patch
    bzip2-1.0.2-progress.patch
    bzip2-1.0.3-no-test.patch
    saneso.patch
)
