# Auto-generated by scripts/sync-alpine.sh
# Source: Alpine Linux aports (main/coreutils)
# Package: coreutils 9.8-r1
# Generated: 2026-02-27T21:58:26Z

set(ALPINE_PKGNAME "coreutils")
set(ALPINE_PKGVER "9.8")

set(ALPINE_SOURCE_URLS
    "https://ftp.gnu.org/gnu/coreutils/coreutils-9.8.tar.xz"
)
set(ALPINE_SOURCE_FILENAME "coreutils-9.8.tar.xz")
set(ALPINE_SOURCE_SHA512 7b6c420907f0e33e4aff3dd92270f8cbd3e94b2ae8cf7caa2d5d1cfd5e9958319904a6547127abd55ee63aae0316f5b1228586b2da34ea402da032e925a25e53)

set(ALPINE_PATCHES
    renameat2-fakeroot.patch
    tail-fix-trailing-larger-number-of-lines-in-regular-files.patch
)
