# Auto-generated by scripts/sync-alpine.sh
# Source: Alpine Linux aports (main/wget)
# Package: wget 1.25.0-r2
# Generated: 2026-02-27T21:58:57Z

set(ALPINE_PKGNAME "wget")
set(ALPINE_PKGVER "1.25.0")

set(ALPINE_SOURCE_URLS
    "https://ftp.gnu.org/gnu/wget/wget-1.25.0.tar.gz"
)
set(ALPINE_SOURCE_FILENAME "wget-1.25.0.tar.gz")
set(ALPINE_SOURCE_SHA512 a7ce33c07a1a206a8574b6e9ea7cc5292315df0914edbcf05a014d35ae9e3d24699a46818b409b884ada57428cf30502f4bbb3767cae2c6934e4e7fb2d0c5036)

set(ALPINE_PATCHES)
