# Auto-generated by scripts/sync-alpine.sh
# Source: Alpine Linux aports (main/gawk)
# Package: gawk 5.3.2-r2
# Generated: 2026-02-27T21:58:26Z

set(ALPINE_PKGNAME "gawk")
set(ALPINE_PKGVER "5.3.2")

set(ALPINE_SOURCE_URLS
    "https://ftp.gnu.org/gnu/gawk/gawk-5.3.2.tar.xz"
)
set(ALPINE_SOURCE_FILENAME "gawk-5.3.2.tar.xz")
set(ALPINE_SOURCE_SHA512 2268150fa35ae049a6ff3d0d0fa110db10477014c25f50e2ab4e3ee5fd60133369d2a994f59db4eb718020a0af5c4003ae7278c63e7fffa72f431ff4a1429e48)

set(ALPINE_PATCHES
    echild-strerror.patch
)
