# Auto-generated by scripts/sync-alpine.sh
# Source: Alpine Linux aports (main/iproute2)
# Alpine branch: 3.23-stable
# Package: iproute2 6.17.0-r0
# Generated: 2026-03-03T17:59:00Z

set(ALPINE_PKGNAME "iproute2")
set(ALPINE_PKGVER "6.17.0")

set(ALPINE_SOURCE_URLS
    "https://kernel.org/pub/linux/utils/net/iproute2/iproute2-6.17.0.tar.xz"
)
set(ALPINE_SOURCE_FILENAME "iproute2-6.17.0.tar.xz")
set(ALPINE_SOURCE_SHA512 3d83d49233c1d984f15d285a46e2ec0eeb820c7cb84cfc84866921f37e8a57d31bc3953be07e8c79ed6079f326a25c3a85f591b0d67f9f689c0c70ccdb0fef77)

set(ALPINE_PATCHES
    bridge-avoid-redefinition-of-in6_addr.patch
    includes.patch
)
