# Auto-generated by scripts/sync-alpine.sh
# Source: Alpine Linux aports (main/patch)
# Package: patch 2.8-r0
# Generated: 2026-02-27T21:58:27Z

set(ALPINE_PKGNAME "patch")
set(ALPINE_PKGVER "2.8")

set(ALPINE_SOURCE_URLS
    "https://ftp.gnu.org/gnu/patch/patch-2.8.tar.xz"
)
set(ALPINE_SOURCE_FILENAME "patch-2.8.tar.xz")
set(ALPINE_SOURCE_SHA512 d689d696660a662753e8660792733c3be0a94c76abfe7a28b0f9f70300c3a42d6437d081553a59bfde6e1b0d5ee13ed89be48d0b00b6da2cadbfc14a15ada603)

set(ALPINE_PATCHES)
