# Auto-generated by scripts/sync-alpine.sh
# Source: Alpine Linux aports (main/sharutils)
# Package: sharutils 4.15.2-r6
# Generated: 2026-02-27T21:58:27Z

set(ALPINE_PKGNAME "sharutils")
set(ALPINE_PKGVER "4.15.2")

set(ALPINE_SOURCE_URLS
    "https://ftp.gnu.org/gnu/sharutils/sharutils-4.15.2.tar.xz"
)
set(ALPINE_SOURCE_FILENAME "sharutils-4.15.2.tar.xz")
set(ALPINE_SOURCE_SHA512 80d0b804a0617e11e5c23dc0d59b218bbf93e40aaf5e9a5401a18ef9cb700390aab711e2b2e2f26c8fd5b8ef99a91d3405e01d02cadabcba7639979314e59f8d)

set(ALPINE_PATCHES
    format-security.patch
    gcc-10.patch
    Backport-stdbool.m4-from-gnulib-devel-0-52.2.patch
    Port-getcwd.m4-to-ISO-C23.patch
    Port-the-code-to-ISO-C23.patch
)
