# Auto-generated by scripts/sync-alpine.sh
# Source: Alpine Linux aports (main/gzip)
# Package: gzip 1.14-r2
# Generated: 2026-02-27T21:58:26Z

set(ALPINE_PKGNAME "gzip")
set(ALPINE_PKGVER "1.14")

set(ALPINE_SOURCE_URLS
    "https://ftp.gnu.org/gnu/gzip/gzip-1.14.tar.xz"
)
set(ALPINE_SOURCE_FILENAME "gzip-1.14.tar.xz")
set(ALPINE_SOURCE_SHA512 82aef53188b3e69b51b7ddab5b8c44a11a5b73c0039b22a315a0c7d244694feab0146748add4265901eb1b4c0cee8a9eb69594995f098830d964091af97079c5)

set(ALPINE_PATCHES)
