# Auto-generated by scripts/sync-alpine.sh
# Source: Alpine Linux aports (main/lsof)
# Package: lsof 4.99.5-r0
# Generated: 2026-02-27T21:58:27Z

set(ALPINE_PKGNAME "lsof")
set(ALPINE_PKGVER "4.99.5")

set(ALPINE_SOURCE_URLS
    "https://github.com/lsof-org/lsof/archive/4.99.5/lsof-4.99.5.tar.gz"
)
set(ALPINE_SOURCE_FILENAME "lsof-4.99.5.tar.gz")
set(ALPINE_SOURCE_SHA512 083ff93545e02ad6c71ca77fbe7f90b25f09a2630472558e09a7784316d74d36cac42e158596444e1a69ffb848f4dd4c7f0fbac63bd0c9d02adfe423a838034a)

set(ALPINE_PATCHES
    hassecurity.patch
)
