# Auto-generated by scripts/sync-alpine.sh
# Source: Alpine Linux aports (main/findutils)
# Package: findutils 4.10.0-r0
# Generated: 2026-02-27T21:58:26Z

set(ALPINE_PKGNAME "findutils")
set(ALPINE_PKGVER "4.10.0")

set(ALPINE_SOURCE_URLS
    "https://ftp.gnu.org/pub/gnu/findutils/findutils-4.10.0.tar.xz"
)
set(ALPINE_SOURCE_FILENAME "findutils-4.10.0.tar.xz")
set(ALPINE_SOURCE_SHA512 b8b683d21cd26c6da4f41c56e83cadbda4780f8610a2bbd4b4e34bb1f339c3209721974b03e076d5eef0331fd876d947b398197aad37c29bbcc2e0405c641b34)

set(ALPINE_PATCHES
    test-parse-datetime.patch
    test-sigusr.patch
)
