#!/bin/sh
# generate-certs.sh - Download Mozilla CA bundle and generate C header
#
# Downloads the Mozilla CA certificate bundle from curl.se and converts
# it into a C header file containing the PEM data as a string literal.
# This is used by the SSL variant to embed trusted CA certs directly
# into the binary.

set -eu

CERT_URL="https://curl.se/ca/cacert.pem"
OUT_DIR="${1:-src}"
OUT_FILE="$OUT_DIR/embedded_certs.h"

echo "Downloading Mozilla CA bundle from $CERT_URL..."
curl -fsSL -o /tmp/cacert.pem "$CERT_URL"

echo "Generating $OUT_FILE..."

cat > "$OUT_FILE" << 'HEADER_TOP'
/*
 * embedded_certs.h - Mozilla CA certificate bundle
 *
 * AUTO-GENERATED by scripts/generate-certs.sh - DO NOT EDIT
 *
 * This file contains the Mozilla CA certificate bundle in PEM format,
 * embedded as a C string literal. It is compiled into the busyq-ssl
 * binary so that HTTPS works without a system certificate store.
 */

#ifndef BUSYQ_EMBEDDED_CERTS_H
#define BUSYQ_EMBEDDED_CERTS_H

static const char busyq_embedded_cacerts[] =
HEADER_TOP

# Convert PEM file to a C string literal.
# Each line becomes a quoted string with \n appended.
sed 's/\\/\\\\/g; s/"/\\"/g; s/^/    "/; s/$/\\n"/' /tmp/cacert.pem >> "$OUT_FILE"

cat >> "$OUT_FILE" << 'HEADER_BOTTOM'
    ;

static const unsigned long busyq_embedded_cacerts_len =
    sizeof(busyq_embedded_cacerts) - 1;

#endif /* BUSYQ_EMBEDDED_CERTS_H */
HEADER_BOTTOM

rm -f /tmp/cacert.pem

echo "Generated $OUT_FILE ($(wc -l < "$OUT_FILE") lines)"
