# Auto-generated by scripts/sync-alpine.sh
# Source: Alpine Linux aports (main/libmnl)
# Alpine branch: 3.23-stable
# Package: libmnl 1.0.5-r2
# Generated: 2026-03-03T17:59:00Z

set(ALPINE_PKGNAME "libmnl")
set(ALPINE_PKGVER "1.0.5")

set(ALPINE_SOURCE_URLS
    "https://www.netfilter.org/projects/libmnl/files/libmnl-1.0.5.tar.bz2"
)
set(ALPINE_SOURCE_FILENAME "libmnl-1.0.5.tar.bz2")
set(ALPINE_SOURCE_SHA512 16fa48e74c9da7724a85c655dfb0abd8369392627934639d65de951543e1447ac3e048d231248f1ce8861443c2ef62654a85a81feeedbbffaf2e5744f6cf4c9f)

set(ALPINE_PATCHES
    musl-fix-headers.patch
)
