# Auto-generated by scripts/sync-alpine.sh
# Source: Alpine Linux aports (main/tar)
# Package: tar 1.35-r4
# Generated: 2026-02-27T21:58:27Z

set(ALPINE_PKGNAME "tar")
set(ALPINE_PKGVER "1.35")

set(ALPINE_SOURCE_URLS
    "https://ftp.gnu.org/gnu/tar/tar-1.35.tar.xz"
)
set(ALPINE_SOURCE_FILENAME "tar-1.35.tar.xz")
set(ALPINE_SOURCE_SHA512 8b84ed661e6c878fa33eb5c1808d20351e6f40551ac63f96014fb0d0b9c72d5d94d8865d39e36bcb184fd250f84778a3b271bbd8bd2ceb69eece0c3568577510)

set(ALPINE_PATCHES
    ignore-apk-tools-checksums.patch
)
