# Auto-generated by scripts/sync-alpine.sh
# Source: Alpine Linux aports (main/which)
# Package: which 2.23-r0
# Generated: 2026-02-27T21:58:57Z

set(ALPINE_PKGNAME "which")
set(ALPINE_PKGVER "2.23")

set(ALPINE_SOURCE_URLS
    "https://ftp.gnu.org/gnu/which/which-2.23.tar.gz"
)
set(ALPINE_SOURCE_FILENAME "which-2.23.tar.gz")
set(ALPINE_SOURCE_SHA512 738807f79e8cfc5967541a28ae7021247c04c4177279f09be2c19c069af450a7e3b19baf9079fe5569b25b4630bb400be242a123647e52c9fe54f0ad007317bf)

set(ALPINE_PATCHES
    gcc15.patch
)
