# Auto-generated by scripts/sync-alpine.sh
# Source: Alpine Linux aports (main/unzip)
# Package: unzip 6.0-r16
# Generated: 2026-02-27T12:42:29Z

set(ALPINE_PKGNAME "unzip")
set(ALPINE_PKGVER "6.0")

set(ALPINE_SOURCE_URLS
    "https://dev.alpinelinux.org/archive/unzip/unzip60.tgz"
)
set(ALPINE_SOURCE_FILENAME "unzip60.tgz")
set(ALPINE_SOURCE_SHA512 0694e403ebc57b37218e00ec1a406cae5cc9c5b52b6798e0d4590840b6cdbf9ddc0d9471f67af783e960f8fa2e620394d51384257dca23d06bcd90224a80ce5d)

set(ALPINE_PATCHES
    08-allow-greater-hostver-values.patch
    10-unzip-handle-pkware-verify.patch
    13-remove-build-date.patch
    20-unzip-uidgid-fix.patch
    21-fix-warning-messages-on-big-files.patch
    unzip-6.0-exec-shield.patch
    unzip-6.0-format-secure.patch
    unzip-6.0-heap-overflow-infloop.patch
    unzip-6.0-timestamp.patch
    CVE-2014-8139.patch
    CVE-2014-8140.patch
    CVE-2014-8141.patch
    CVE-2014-9636.patch
    CVE-2014-9913.patch
    CVE-2016-9844.patch
    CVE-2018-1000035.patch
    CVE-2018-18384.patch
    large-symlinks.patch
    CVE-2021-4217.patch
    CVE-2022-0529-and-CVE-2022-0530.patch
    zipbomb-manpage.patch
    zipbomb-part1.patch
    zipbomb-part2.patch
    zipbomb-part3.patch
    zipbomb-part4.patch
    zipbomb-part5.patch
    zipbomb-part6.patch
    zipbomb-part7.patch
    zipbomb-switch.patch
    gcc15.patch
)
