# Auto-generated by scripts/sync-alpine.sh
# Source: Alpine Linux aports (main/zip)
# Package: zip 3.0-r13
# Generated: 2026-02-27T21:58:57Z

set(ALPINE_PKGNAME "zip")
set(ALPINE_PKGVER "3.0")

set(ALPINE_SOURCE_URLS
    "https://downloads.sourceforge.net/infozip/zip30.tar.gz"
)
set(ALPINE_SOURCE_FILENAME "zip30.tar.gz")
set(ALPINE_SOURCE_SHA512 c1c3d62bf1426476c0f9919b568013d6d7b03514912035f09ee283226d94c978791ad2af5310021e96c4c2bf320bfc9d0b8f4045c48e4667e034d98197e1a9b3)

set(ALPINE_PATCHES
    10-zip-3.0-build.patch
    20-zip-3.0-exec-stack.patch
    30-zip-3.0-pic.patch
    40-fix-zipnote.patch
    format-security.patch
    configure-gcc14.patch
)
