# Auto-generated by scripts/sync-alpine.sh
# Source: Alpine Linux aports (community/time)
# Package: time 1.9-r1
# Generated: 2026-02-27T21:58:57Z

set(ALPINE_PKGNAME "time")
set(ALPINE_PKGVER "1.9")

set(ALPINE_SOURCE_URLS
    "https://ftp.gnu.org/gnu/time/time-1.9.tar.gz"
)
set(ALPINE_SOURCE_FILENAME "time-1.9.tar.gz")
set(ALPINE_SOURCE_SHA512 5c6dabbbe71e9103a47b892b86bb914c1704122d4fe7dff1e2cbd28503297163118d295077d8e062b035d673a1f91c36f8a45c7383f374fd766942b32bde4406)

set(ALPINE_PATCHES
    0001-Fix-signature-of-signal-handler.patch
)
