# Auto-generated by scripts/sync-alpine.sh
# Source: Alpine Linux aports (main/procps-ng)
# Package: procps-ng 4.0.5-r0
# Generated: 2026-02-27T21:58:27Z

set(ALPINE_PKGNAME "procps-ng")
set(ALPINE_PKGVER "4.0.5")

set(ALPINE_SOURCE_URLS
    "https://sourceforge.net/projects/procps-ng/files/Production/procps-ng-4.0.5.tar.xz/download"
)
set(ALPINE_SOURCE_FILENAME "procps-ng-4.0.5.tar.xz")
set(ALPINE_SOURCE_SHA512 c27730743210cf850c4af98e1fb81bc8ee8d550b07b9eedb34a5b9d661263d0f1bc92c4e73802a0ed8d4405854aef4bc542bff283c28e8fbb6dabb967f9e4359)

set(ALPINE_PATCHES
    disable-test_pids-check.patch
)
