# Auto-generated by scripts/sync-alpine.sh
# Source: Alpine Linux aports (main/bash)
# Package: bash 5.3.3-r1
# Generated: 2026-02-27T21:58:26Z

set(ALPINE_PKGNAME "bash")
set(ALPINE_PKGVER "5.3.3")

set(ALPINE_SOURCE_URLS
    "https://ftp.gnu.org/gnu/bash/bash-5.3.tar.gz"
)
set(ALPINE_SOURCE_FILENAME "bash-5.3-1.tar.gz")
set(ALPINE_SOURCE_SHA512 426702c8b0fb9e0c9956259973ce5b657890fd47f4f807a64febf20077bb48d0b91474ed6e843d2ef277186b46c5fffa79b808da9b48d4ec027d5e2de1b28ed8)

set(ALPINE_PATCHES
    bash-noinfo.patch
)
